### PR TITLE
documentation updates

### PR DESCRIPTION
**Pull request by qwo**

### CODE REVIEW

**Comment by qwo** [comment]
@tealtail is there anything else I could  contribute to improve this PR?

**Comment by tealtail** [comment]
Thanks @stanzheng can you take a look at the config.js set up part of the doc that tripped you up (invokeUrl needing to be the base url, without `/ride`) and try to make that a bit more clear to new eyes

**Comment by qwo** [comment]
@tealtail I just swapped around the config object and detailed how to get the cognito steps. I think you were clear just the ordering of the steps I misread the url part. 

I could add a note about CORS but I think it was just me completely not reading the snippet you detailed.

**Comment by tealtail** [comment]
🎉 Thanks @stanzheng !

**Pull request merged**
